# Analyzing Change over Time - Line and Stacked Area Plots

This is the second notebook in the Plotly tutorial series.

Understanding how variables evolve over time is a fundamental task in data analysis. As Albert Cairo discusses in Chapter 8 of *The Truthful Art: Data, Charts and Maps for Communication,* analyzing these temporal changes gives us insight into trends (decrease, increase or or no change), seasonality (consistent and periodic fluctuations), and noise (variations due to random change)

In this notebook, we'll explore how to use Plotly to create effective visualizations for time series data. We'll focus on two related types of visualizations.
- **Line plots**: best for tracking individual variables over time
- **Stacked area charts**: useful for visualizing parts of a whole as they evolve

Specifically, this notebook covers:
- Creating basic line and area plots
- Visualizing multiple time series in a clean, readable way
- Customizing layout, colors, and interactivity
- Best practices for visualizations that analyze change over time

We will be using the [CO2 emissions](https://www.kaggle.com/datasets/ravindrasinghrana/carbon-co2-emissions) dataset found in the [data](../data) directory.

In [1]:
# Imports
import pandas as pd
import numpy as np
import plotly.express as px
import statsmodels

## Lineplots

First, let's create the most barebones lineplot. Let's read in our data:

In [37]:
df = pd.read_csv('../data/co2_emissions.csv')
df.head()

       Country Region        Date  Kilotons of Co2  Metric Tons Per Capita
0  Afghanistan   Asia  01-01-2011           8930.0                    0.31
1  Afghanistan   Asia  01-01-2012           8080.0                    0.27
2  Afghanistan   Asia  01-01-2010           7110.0                    0.25
3  Afghanistan   Asia  01-01-2019           6080.0                    0.16
4  Afghanistan   Asia  01-01-2018           6070.0                    0.17

We can see that the dates are arranged in the mm-dd-yyyy format, but since the are sampled once each year, we really only need the year value. Let's clean our dataset to make it easier to plot.

In [38]:
# Extract year to new column
df['Date'] = pd.to_datetime(df['Date'], format='%d-%m-%Y')
df['Year'] = df['Date'].dt.year
df = df.sort_values(by='Year')
df.head()

,Country,Region,Date,Kilotons of Co2,Metric Tons Per Capita,Year
30,Albania,Europe,1990-01-01,5980.0,1.82,1990
3203,Mauritius,Africa,1990-01-01,1160.0,1.10,1990
12,Afghanistan,Asia,1990-01-01,2380.0,0.22,1990
5628,Zambia,Africa,1990-01-01,2740.0,0.36,1990
5586,Vietnam,Asia,1990-01-01,19330.0,0.29,1990

Now, let's plot the CO2 emissions for the United Kingdom over time.

In [39]:
df_uk = df[df['Country'] == 'United Kingdom']
df_uk.head()

,Country,Region,Date,Kilotons of Co2,Metric Tons Per Capita,Year
5378,United Kingdom,Europe,1990-01-01,561770.0,9.81,1990
5377,United Kingdom,Europe,1991-01-01,570680.0,9.94,1991
5379,United Kingdom,Europe,1992-01-01,557890.0,9.69,1992
5385,United Kingdom,Europe,1993-01-01,541380.0,9.38,1993
5387,United Kingdom,Europe,1994-01-01,535180.0,9.25,1994

In [40]:
fig = px.line(df_uk, y="Kilotons of Co2", x="Year", title='Carbon Emissions in the United Kingdom')
fig.show()

Now we can try plotting multiple countries with different colors. We are going to need to filter our dataset again, however.

In [51]:
df_eu = df[df['Country'].isin(['United Kingdom', 'France', 'Germany', "Spain"])]

In [52]:
fig = px.line(df_eu, y="Kilotons of Co2", x="Year", title='Carbon Emissions in Europe', color = 'Country')
fig.show()

For CVD accessibility, we can adjust the markers on the lines as well.

In [53]:
fig = px.line(df_eu, y="Kilotons of Co2", x="Date", title='Carbon Emissions in Europe', 
              
              # Adjust color of line according to data
              color = 'Country', 
              
              # Adjust marker of line according to data
              symbol = 'Country',

              # In addition to the points defined above, if you any other information displayed on the hover label
              hover_data=['Region'],
              
              # Adjust size
              width = 1000, height = 600
              )


fig.show()

From our visualizations, we can see some advantages of Plotly over other other packages when creating lineplots.

- Adjusts y-axis to be readable
- The interactivity from hover labels allowfor us to see individual data points clearly
- Plotly is compatible time values being in MM-DD-YYYY format on the x-axis. We modified it ourselves since they weren't sorted, but this makes the process much more seamless.

## Stacked Area Charts

Stacked area charts are a variation of line charts that show how multiple components contribute to a total over time. They're especially useful when you're interested in both the overall trend and how different categories change relative to one another. So effectively, we can see how different data points contribute to a whole while also observing them over time.

Below, we create a basic stacked area chart from our data using Plotly.

In [65]:
fig = px.area(df, x="Year", y="Kilotons of Co2", 
              
              # Adjusts color according to data
              color="Region", 
              
              # Adjusts what each line in the area chart is showing
              line_group= "Country",
              
              # Adjust layout
              height = 600, width = 1000,

              # Set title
              title = "World Carbon Emissions"
              
              )

fig.show()

One of the advantages of Plotly is that even this kind of visualization can be made CVD accessible by adding symbol fills.

In [70]:
fig = px.area(df, x="Year", y="Kilotons of Co2", 
              
              # Adjusts color according to data
              color="Region",

              # Adjusts what each line in the area chart is showing
              line_group= "Country",
              
              # Adjust the fill symbols according to data
              pattern_shape="Region",
              pattern_shape_sequence=[".", "x", "+"],
              
              # Adjust layout
              height = 600, width = 1000,

              # Set title
              title = "World Carbon Emissions"
              
              )

fig.show()

This can be made nicer by using a cleaner dataset, such as our Europe subset.

In [72]:
fig = px.area(df_eu, x="Year", y="Kilotons of Co2", 
              
              # Adjusts color according to data
              color="Country",
                            
              # Adjust the fill symbols according to data
              pattern_shape="Country",
              pattern_shape_sequence=[".", "x", "+"],
              
              # Adjust layout
              height = 600, width = 1000,

              # Set title
              title = "World Carbon Emissions"
              
              )

fig.show()

## Final Remarks

Line plots and stacked area charts are fundamental tools for analyzing temporal data. In this notebook, we show how Plotly makes it easy to create clean, interactive time series visualizations with minimal code.

- **Line plots** are ideal for tracking the behavior of individual variables over time, revealing trends, cycles, and anomalies with clarity.
- **Stacked area charts** build on that by visualizing how different components contribute to a whole, helping us understand both total change and internal composition.

In the [next notebook](03_barcharts_categorical.ipynb), we will explore how to use Plotly to create bar charts, stacked bar charts, radar charts, and sunburst diagrams to analyze categorical data,and continue applying the principles of effective visual communication.

## References
- [Plotly lineplot documentation](https://plotly.com/python/line-charts/)
- [Plotly stacked area graphs documentation](https://plotly.com/python/filled-area-plots/)
- *The Truthful Art: Data, Charts and Maps for Communication*, Albert Cairo
- *The Visual Display of Quantitative Information*, Edward Tufte